options:
  aux_backup_directory:
    type: string
    default: "/tmp/duplicity"
    description: |
      Specifies an additional directory paths which duplicity will monitor on
      all units for backup.
  full_backup:
    type: boolean
    default: False
    description: |
      When False, duplicity will perform incremental backups and when True, it
      does full backups.
  backend:
    type: string
    default: ""
    description: |
      Accepted values are s3 | ssh | scp | ftp | rsync | file
      An empty string will disable backups.
  remote_backup_url:
    type: string
    default: ""
    description: |
      URL to the remote server and its local path to be used as the
      backup destination.

      Backends and their URL formats:
        file:      'file:///some_dir'
        ftp & sftp: 'remote.host[:port]/some_dir'
        rsync:      'other.host[:port]::/module/some_dir'
                    'other.host[:port]/relative_path'
                    'other.host[:port]//absolute_path'
        s3:         's3:other.host[:port]/bucket_name[/prefix]'
                    's3+http://bucket_name[/prefix]'
        scp:        'other.host[:port]/some_dir'
        ssh:        'other.host[:port]/some_dir'
  aws_access_key_id:
    type: string
    default: ""
    description: |
      Access key id for the AWS IMA user. The user must have a policy that
      grants it privileges to upload to the S3 bucket. This value is required
      when backend='s3'.
  aws_secret_access_key:
    type: string
    default: ""
    description: |
      Secret access key for the AWS IMA user. The user must have a policy that
      grants it privileges to upload to the S3 bucket. This value is required
      when backend='s3'.
  remote_user:
    type: string
    default: ""
    description: |
      This value sets the remote host username for ssh or ftp backups. This is
      required for ftp type backups and optional for ssh, which if unset it
      will default to using the local hosts username.
  remote_password:
    type: string
    default: ""
    description: |
      This value sets the remote server's password to be used for ssh or ftp
      backups. This is required for ftp backups and optional for ssh, which if
      unset may still be able to authenticate via trusted host keys.
  backup_frequency:
    type: string
    default: "manual"
    description: |
      Sets the crontab backup frequency to one of the following values:
      daily|weekly|monthly|manual|auto
      When set to auto, the cron will only backup the files if they have
      changed.
  disable_encryption:
    type: boolean
    default: False
    description: |
      By default, duplicity uses symmetric encryption on backup, requiring a
      simple password. Duplicity also supports asymmetric encryption, via GPG
      keys. Setting this value to True disables encryption across the entire
      application.
  encryption_passphrase:
    type: string
    default: ""
    description: |
      Set a passphrase required to perform symmetric encryption.
  gpg_public_key:
    type: string
    default: ""
    description: |
      Sets the GPG Public Key used for asymmetrical encryption. When set, this
      becomes the primary method for encryption.