options:
  aux-backup-directory:
    type: string
    default: ""
    description: "Specifies a directory path which duplicity will create and
monitor on all units"
  string-option:
    type: string
    default: "Default Value"
    description: "A short description of the configuration option"
  boolean-option:
    type: boolean
    default: False
    description: "A short description of the configuration option"
  int-option:
    type: int
    default: 9001
    description: "A short description of the configuration option"
